services:
  app:
    build: .
    container_name: otp-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mailpit
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - OTP_EXPIRATION_TIME=300
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_USER=you@example.com
      - SMTP_PASS=yourpassword
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  mongo_data:
